name: rns_task
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.2.1 <3.0.0"
analyzer:
  enable-experiment:
    - non-nullable
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true